# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.4-browsers
      - image: circleci/mysql:5.7-ram
        command: [--default-authentication-plugin=mysql_native_password]
        environment:
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: platform_test

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Restore the cache.
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # Run composer update (will only work if cache was empty).
      - run:
          name: Install dependencies
          command: composer install --ignore-platform-reqs

      # Save the installed dependencies in the cache.
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.lock" }}

      # Prepare the test environment for phpunit.
      - run:
          name: Prepare test environment
          command: |
            if [[ ${SKIP_TESTS} != true && ${SKIP_PHPUNIT} != true ]]; then
              cp .circleci/.circleci.env .env
            fi

      # Run grumphp!
      - run:
          name: GrumPHP
          command: vendor/bin/grumphp run --config ./grump-config/grumphp.yml

      # Run PhpUnit!
      - run:
          name: PHPUnit
          command: |
            if [[ ${SKIP_TESTS} == true || ${SKIP_PHPUNIT} == true ]]; then
                echo "Skipping tests!"
            else
                vendor/bin/phpunit
            fi
